### ISSUE TITLE
explanation of result properties

### ISSUE THREAD

**Issue by seiyria** [clux/tournament#25]
In [this section](https://github.com/clux/tournament/blob/master/doc/base.md#trnresults--result), the result properties are described. I can grok `pos` and `wins` - those are pretty self-explanatory. What is `seed`, `for`, and `against` in this case?

**Comment by clux** [comment]
The `.for` and `.against` are sums of scores from the `.m` arrays in matches. For football this would represent goals for/against, in best of N scenarios it would be map wins or map losses respectively.

Seed is the player number (since there's nothing else identifiable in that list sorted mostly by minimally achieved position).

**Comment by seiyria** [comment]
So basically, `for` is "my total score" and `against` is "the sum of all my opponents scores"?

**Comment by clux** [comment]
Yes. Specifically, the latter is the sum of all my opponents scores versus me.

**Comment by seiyria** [comment]
Gotcha. Thank you!

**Comment by clux** [comment]
Happy to help. :]
